version: '3'

services:
  transferwiser:
    image: endiangroup/transferwiser:latest
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - TRANSFERWISER_PORT=3000
      - TRANSFERWISER_TWHOST=sandbox.transferwise.tech
