version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  transferwiser:
    image: endiangroup/transferwiser:latest
    build: 
      context: .
      dockerfile: ./transferwiser.Dockerfile
    depends_on:
      - redis
    environment: 
      - TRANSFERWISER_PORT=3000
      - TRANSFERWISER_REDISADDR=redis:6379
      - TRANSFERWISER_TWHOST=sandbox.transferwise.tech
      - TRANSFERWISER_TWLOGINREDIRECT=http://localhost:8443/oauth/callback
      - TRANSFERWISER_TWCLIENTID=endiangroup/transferwiser_dev

  ssl_proxy:
    image: endiangroup/transferwiser_proxy:latest
    build: 
      context: .
      dockerfile: ./proxy.Dockerfile
    depends_on:
      - transferwiser
    volumes:
      - ./proxy:/etc/nginx/certs
    ports:
      - 8080:80
      - 8443:443
