// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/endiangroup/transferwiser/core"
import mock "github.com/stretchr/testify/mock"

// TransferwiseAuthenticator is an autogenerated mock type for the TransferwiseAuthenticator type
type TransferwiseAuthenticator struct {
	mock.Mock
}

// RedirectUrl provides a mock function with given fields:
func (_m *TransferwiseAuthenticator) RedirectUrl() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: code
func (_m *TransferwiseAuthenticator) RefreshToken(code string) (*core.RefreshTokenData, error) {
	ret := _m.Called(code)

	var r0 *core.RefreshTokenData
	if rf, ok := ret.Get(0).(func(string) *core.RefreshTokenData); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.RefreshTokenData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
