// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/endiangroup/transferwiser/core"
import mock "github.com/stretchr/testify/mock"

// TransferwiseAPI is an autogenerated mock type for the TransferwiseAPI type
type TransferwiseAPI struct {
	mock.Mock
}

// Transfers provides a mock function with given fields:
func (_m *TransferwiseAPI) Transfers() ([]*core.Transfer, error) {
	ret := _m.Called()

	var r0 []*core.Transfer
	if rf, ok := ret.Get(0).(func() []*core.Transfer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Transfer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
